-- Rename Role enum values: COLLABORATOR → COLLABORATEUR, SUPER_ADMIN → DIRECTION
ALTER TYPE "Role" RENAME VALUE 'COLLABORATOR' TO 'COLLABORATEUR';
ALTER TYPE "Role" RENAME VALUE 'SUPER_ADMIN' TO 'DIRECTION';

-- Update column default to new enum value name
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT 'COLLABORATEUR'::"Role";
